#!/usr/bin/env bash

TMP="/tmp/file"
README="./README.md"

echo "Generating README.md..."
echo > $TMP # Clear file

for file in *.md; do
  if [ $file != "README.md" ]; then
    cat $file >> $TMP
  fi
done

# https://github.com/ekalinin/github-markdown-toc
add-toc $TMP > $README # Add Toc
prettier -w $README # Format
git add $README # Add to commit


